---
title: "Rapid assessments and surveys in R"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE, 
                      collapse = TRUE, 
                      comment = "#>", 
                      fig.path = "inst/images", 
                      fig.align = "right") 
```


## Overview

This [repository](https://github.com/EPIET/RapidAssessmentSurveys) hosts the R 
learning materials for the EPIET Rapid Assessments and Surveys (RAS) module.  

The module includes two computer-based case studies: one for conducting survey 
analysis on vaccination coverage data from Greece, and another on population 
estimates from GIS sampling in Sudan. 

Credits go to the original authors of the case study, as well as the contributors
who subsequently created and adapted the R companion guide (see version history 
in the guide for the list of authors and contributors).  The guide is reviewed 
and updated annually.

These case studies are covered by a Gnu General Public Licence version 3 (GPL-3).
Please read the [licence conditions](https://github.com/EPIET/RapidAssessmentSurveys/blob/master/LICENSE) before using or distributing this case study.

## Vaccination coverage case study 
To follow this case study, you will first need the participant pack, which can 
be downloaded [here](https://github.com/EPIET/RapidAssessmentSurveys/raw/master/docs/RAS_VCE_R_guide_2022.zip).  

You can then access the R guide for this case study in two ways:

- Click on [this link](https://epiet.github.io/RapidAssessmentSurveys/RAS_VCE_R_guide_2022.html) 
to open the guide online in your internet browser (internet connection required)
- The guide is also available in HTML, Microsoft Word and .pdf format in the 
`guide` folder of the participant pack

## Population estimates case study
To follow this case study, you will first need the participant pack, which can 
be downloaded [here](https://github.com/EPIET/RapidAssessmentSurveys/raw/master/docs/gis_sampling.zip).  

You can then access the R guide for this case study in two ways:

- Click on [this link](https://epiet.github.io/RapidAssessmentSurveys/gis_sampling.html) 
to open the guide online in your internet browser (internet connection required)

We recommend you use the HTML versions of these guides (either online or off-line)
as it is easier to navigate between the sections, however if you prefer, you can
also print out the .pdf or Microsoft Word versions.


Comments and suggestions are welcome.  If you have found a bug in the case study 
code, please raise an issue about it [here](https://github.com/EPIET/RapidAssessmentSurveys/issues), 
clearly stating the nature of the problem and providing a reproducible example.
You can also use the **issues** page to suggest new features or topics to cover 
in a future version. 