---
title: "EPIET case study: vaccination survey analysis in R"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE, 
                      collapse = TRUE, 
                      comment = "#>", 
                      fig.path = "inst/images", 
                      fig.align = "right") 
```


## Overview

This repository hosts the R learning materials for the EPIET Rapid Assessments and Surveys (RAS) module.  In particular, you will find the R case study guide for conducting survey analysis on vaccination coverage data from Greece.  Data sets and other associated materials are also included. 

A HTML version of the latest guide can be accessed online [here](https://epiet.github.io/RapidAssessmentSurveys/). We recommend you use the HTML version of this guide as it is easier to navigate, however if you prefer, you can also download the .pdf or Microsoft Word versions from the **guide** folder.

Comments and suggestions are welcome.  If you have found a bug in the case study code, please raise an issue about it [here](https://github.com/EPIET/RapidAssessmentSurveys/issues), clearly stating the nature of the problem and providing a reproducible example. You can also use the **issues** page to suggest new features or topics to cover in a future version. 